rango/urls.py
from django.conf.urls import url
from rango import views


app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^register/$', views.register, name='register')
]

tango_with_django_project/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Category, Page, UserProfile
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startsWith('https://'):
            url = 'https://' + url
            cleaned_data['url'] = url

            return url

    class Meta:
        model = Page
        exclude = ('category',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist

from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm


def index(request):
    categories_list = Category.objects.order_by('-likes')[:5]
    pages_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': categories_list, 'pages': pages_list}

    return render(request, 'rango/index.html', context=context_dict)


def about(request):
    return render(request, 'rango/about.html')


def show_category(request, category_name_slug):

    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)

        pages = Page.objects.filter(category=category)

        context_dict['category'] = category
        context_dict['pages'] = pages

    except ObjectDoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context=context_dict)


def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)

    else:
        print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


def add_page(request, category_name_slug):

    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        print("none")
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)

        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}

    return render(request, 'rango/add_page.html', context_dict)


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

templates/rango/about.html
<!DOCTYPE html >
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load rango_template_tags %}

{% block title_block %}
  About
{% endblock %}

{% block body_block %}
  <h1>Rango says...</h1><br>
  <div>
    This tutorial has been put together by Faye. <br>
    <img src="{% static "images/cat.jpg" %}" alt="Happy man in bath not cat">
  </div>
{% endblock %}

templates/rango/add_category.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load rango_template_tags %}

{% block title_block %}
  Add Category
{% endblock %}

{% block body_block %}
  <h1>Add a Category</h1>
  <div>
    <form id="category_form" method="post" action="/rango/add_category/">
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
        {{ hidden }}
      {% endfor %}
      {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
      {% endfor %}
      <input type="submit" name="submit" value="Create Category" />
    </form>
  </div>
{% endblock %}

templates/rango/add_page.html
<!DOCTYPE html>

<html>
  <head>
    <title>Rango</title>
  </head>

  <body>
    <h1>Add a Page</h1>
    <div>
      {% if category %}
        <form id="page_form" method="post" action="/rango/add_page/">
          {% csrf_token %}
          {% for hidden in form.hidden_fields %}
            {{ hidden }}
          {% endfor %}
          {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
          {% endfor %}
          <input type="submit" name="submit" value="Create Page" />
        </form>
      {% else %}
        <p>A category by this name does not exist.</p>
      {% endif %}
    </div>
  </body>
</html>

templates/rango/base.html
<!DOCTYPE html>
{% load rango_template_tags %}

<html>
  <head lang="en">
    <meta charset="utf-8">
    <title>Rango-
      {% block title_block %}
        How to Tango With Django!
      {% endblock %}
    </title>
  </head>
  <body>
    <div>
      {% block sidebar_block %}
        {% get_category_list category %}
      {% endblock %}
    </div>
    <div>
      {% block body_block %}
      {% endblock %}
    </div>
    <hr>
    <div>
      <ul>
        <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
        <li><a href="{% url 'rango:about' %}">About</a></li>
        <li><a href="{% url 'rango:index' %}">Index</a></li>
        <li><a href="{% url 'rango:register' %}">Register</a></li>
      </ul>
    </div>
  </body>
</html>

templates/rango/category.html
<!DOCTYPE html>

{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load rango_template_tags %}

{% block title_block %}
  {{ category.name }}
{% endblock %}

{% block body_block %}
  {% if category %}
    <h1>{{ category.name }}</h1>

    {% if pages %}
      <ul>
        {% for page in pages %}
          <li><a href="{{ page.url }}">{{page.title}}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <strong>No pages currently in category</strong>
    {% endif %}

  {% else %}
    The specified category does not exist! <br>
  {% endif %}
{% endblock %}

templates/rango/cats.html
<!DOCTYPE html >
{% load rango_template_tags %}

{% for c in cats %}
  {% if c == act_cat %}
    <li>
      <strong>
        <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
      </strong>
    </li>
  {% else %}
    <li>
      <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
    </li>
  {% endif %}
{% endfor %}

templates/rango/draft_prech8_add_category.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
{% endblock %}

{% block body_block %}
{% endblock %}

<html>
  <head>
    <title>Rango</title>
  </head>
  <body>
    <h1>Add a Category</h1>
    <div>
      <form id="category_form" method="post" action="/rango/add_category/">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
          {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
          {{ field.errors }}
          {{ field.help_text }}
          {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category" />
      </form>
    </div>
  </body>
</html>

templates/rango/draft_prech8_add_page.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Add Page
{% endblock %}

{% block body_block %}
  <h1>Add a Page</h1>
  <div>
    {% if category %}
      <form id="page_form" method="post" action="/rango/add_page/">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
          {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
          {{ field.errors }}
          {{ field.help_text }}
          {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Page" />
      </form>
    {% else %}
      <p>A category by this name does not exist.</p>
    {% endif %}
  </div>
{% endblock %}

templates/rango/draft_prech8_category.html
<!DOCTYPE html>

{% entends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {{ category.name }}
{% endblock %}

{% block body_block %}
  {% if category %}
    <h1>{{ category.name }}</h1>

    {% if pages %}
      <ul>
        {% for page in pages %}
          <li><a href="{{ page.url }}">{{page.title}}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <strong>No pages currently in category</strong>
    {% endif %}

  {% else %}
    The specified category does not exist! <br>
  {% endif %}
{% endblock %}



<html>
  <head>
    <title>Rango</title>
  </head>
  <body>
    <a href="/">Back to Index Page</a>
    <div>
    {% if category %}
      <h1>{{ category.name }}</h1>
      {% if pages %}
        <ul>
          {%for page in pages %}
            <li><a href="{{ page.url }}">{{page.title}}</a></li>
          {% endfor %}
        </ul>
        <a href="/rango/category/{{ category.slug }}/add_page/">Add a New Page</a>
      {% else %}
        <strong>No pages currently in the category.</strong>
      {% endif %}
    {% else %}
      The specified category does not exist! <br>
    {% endif %}
    </div>
  </body>
</html>

templates/rango/draft_prech8_index.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Index
{% endblock %}

{% block body_block %}
  <h1>Rango says...</h1><br>
  <p>hey there partner!</p>
  <div>
    <strong>Most Liked Categories</strong>
    {% if categories %}
    <ul>
      {% for category in categories %}
      <li><a href="rango/category/{{ category.slug }}/">{{ category.name }}</a></li>
      {% endfor %}
    </ul>
    {% else %}
    <p>There are no categories present.</p>
    {% endif %}
  </div>
  <div>
    <strong>Most Liked Pages</strong><br>
    {% if pages %}
    <ul>
      {% for page in pages %}
      <li>{{ page.title }}</li>
      {% endfor %}
    </ul>
    {% else %}
    <p>There are no pages present.</p>
    {% endif %}
    <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
  </div>

{% endblock %}

<html>
  <head>
    <title>Rango</title>
  </head>

  <body>
    <h1>Rango says...</h1><br>
    <p>hey there partner!</p>
    <div>
      <strong>Most Liked Categories</strong>
      {% if categories %}
      <ul>
        {% for category in categories %}
        <li><a href="rango/category/{{ category.slug }}/">{{ category.name }}</a></li>
        {% endfor %}
      </ul>
      {% else %}
      <p>There are no categories present.</p>
      {% endif %}
    </div>
    <div>
      <strong>Most Liked Pages</strong><br>
      {% if pages %}
      <ul>
        {% for page in pages %}
        <li>{{ page.title }}</li>
        {% endfor %}
      </ul>
      {% else %}
      <p>There are no pages present.</p>
      {% endif %}
    </div>
    <div>
      <a href="/rango/add_category/">Add a New Category</a><br>
    </div>
    <div>
      <a href="/rango/about">About Rango</a><br>
      <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
    </div>
  </body>
</html>

templates/rango/index.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load rango_template_tags %}

{% block title_block %}
  Index
{% endblock %}

{% block body_block %}
  <h1>Rango says...</h1><br>
  <p>hey there partner!</p>
  <div>
    <strong>Most Liked Categories</strong>
    {% if categories %}
    <ul>
      {% for category in categories %}
      <li><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
      {% endfor %}
    </ul>
    {% else %}
    <p>There are no categories present.</p>
    {% endif %}
  </div>
  <div>
    <strong>Most Liked Pages</strong><br>
    {% if pages %}
    <ul>
      {% for page in pages %}
      <li><a href="{{ page.url }}">{{ page.title }}</a></li>
      {% endfor %}
    </ul>
    {% else %}
    <p>There are no pages present.</p>
    {% endif %}
    <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
  </div>

{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  Register
{% endblock %}

{% block body_block %}
  <h1>Register for Rango</h1>
  {% if registered %}
    Rango says: <strong>thank you for registering!</strong>
    <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
  {% else %}
    Rango says: <strong>register here!</strong><br />
    <form id="user_form" method="post" action="{% url 'rango:register' %}"
      enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="submit" value="Register" />
    </form>
  {% endif %}
{% endblock %}